### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by jonwgeorge** [daylightstudio/FUEL-CMS-Forms-Module#8]
What permissions should I be giving to my clients? I gave them 'forms' and 'entries' and it appears to work, but they are unable to edit forms without breaking the form.

**Comment by daylightstudio** [comment]
The permissions should get installed if you use the command line and cd to the same folder as where the index.php CI bootstrap file is and run the following:
```
php index.php fuel/installer/install forms
```
However, in your case, you will need to comment out the contents of the fuel/modules/forms/install/forms_install.sql since the tables have already been installed in order for it to run without errors.

Alternatively, you can create the following permissions manually (which is what will happen if your run the above command line) forms/create, forms/edit, forms/publish, forms/delete, form_entries/create, form_entries/edit, form_entries/delete
